In [10]:

import torch.nn as nn
import torch

In [11]:
# device = 'cuda' if torch.cuda.is_available() else 'cpu'
# block=Encoder_cifar10(80,device)
# img=torch.randn(128,3,32,32)
# img.shape

In [12]:
# block

In [13]:
# out,_,_=block(img)
# out.shape

In [14]:
# from cVAE_GAN_cifar10 import ConditionalBatchNorm2d
# num_features = 64  # 输入特征的通道数
# num_conditions = 10  # 类别数
# cbn=ConditionalBatchNorm2d(64,10)
# cbn

In [15]:

# condition = torch.zeros(32,10)  # 32样本的标签
# condition.shape
# condition


In [16]:
# input_data = torch.randn(32, num_features, 32, 32)
# input_data.shape


In [17]:
# output = cbn(input_data, condition)
# output.shape

In [18]:
from cVAE_GAN_cifar10 import Decoder_cifar10,Encoder_cifar10
device = 'cuda' if torch.cuda.is_available() else 'cpu'
encoder=Encoder_cifar10(device=device)
decoder=Decoder_cifar10(device=device)
img=torch.randn(32,3,32,32).to(device)
z,_,_=encoder(img)



In [19]:
z

tensor([[-2.0597, -0.9218, -0.1266,  ...,  0.7105,  1.3707, -0.8398],
        [ 0.9761,  2.7230,  0.9776,  ..., -0.4310, -0.9563,  2.5983],
        [-0.8066, -0.1102, -0.7556,  ..., -0.1840,  0.1421, -0.2004],
        ...,
        [-1.1351,  1.6127,  0.9774,  ..., -0.8635, -0.3793,  0.8473],
        [ 1.7913, -0.4197,  1.3579,  ..., -1.2186,  3.3386, -0.7781],
        [ 2.3023, -0.9359, -1.1374,  ...,  0.3954, -1.5244,  0.7262]],
       device='cuda:0', grad_fn=<AddBackward0>)

In [20]:
z.shape

torch.Size([32, 80])

In [21]:
y = torch.randint(low=0, high=9, size=(32,)).to(device)


In [22]:
img=decoder(z,y)

In [23]:
img

tensor([[[[-0.1837, -0.0666,  0.0846,  ...,  0.1840,  0.0119, -0.1444],
          [-0.5079, -0.1437,  0.0432,  ..., -0.0067, -0.1001, -0.0450],
          [-0.4717, -0.0351,  0.0872,  ...,  0.0512, -0.0858,  0.1380],
          ...,
          [-0.2400, -0.2012, -0.2120,  ..., -0.1129, -0.0092,  0.1475],
          [-0.1948, -0.2147, -0.1434,  ..., -0.1183, -0.0095,  0.0768],
          [-0.1430, -0.0754, -0.1828,  ..., -0.2298, -0.2051, -0.0631]],

         [[ 0.3385,  0.3386,  0.2795,  ...,  0.1042, -0.0208, -0.0745],
          [ 0.1893,  0.2477, -0.0961,  ..., -0.5406, -0.5602, -0.5045],
          [ 0.2535,  0.1986, -0.0356,  ..., -0.1773, -0.2610, -0.3186],
          ...,
          [ 0.0908, -0.0255, -0.1415,  ...,  0.1728,  0.2044, -0.0437],
          [ 0.0988,  0.0721, -0.1862,  ...,  0.2106,  0.2744,  0.0922],
          [ 0.0636, -0.1359, -0.0717,  ...,  0.1106,  0.1149,  0.1181]],

         [[ 0.0626,  0.0762, -0.0874,  ..., -0.0680,  0.0155,  0.0031],
          [ 0.3046,  0.2048,  

In [24]:
img.shape

torch.Size([32, 3, 32, 32])

In [25]:
decoder

Decoder_cifar10(
  (linear): Linear(in_features=20, out_features=6144, bias=True)
  (embed): Embedding(10, 128)
  (gen_blocks): ModuleList(
    (0): DecoderBlock(
      (conv): Conv2d(384, 384, kernel_size=(1, 1), stride=(1, 1), padding=same)
      (linear): Linear(in_features=148, out_features=10, bias=True)
      (cbn): ConditionalBatchNorm2d(
        (bn): BatchNorm2d(384, eps=1e-05, momentum=0.1, affine=False, track_running_stats=True)
        (gamma_embed): Linear(in_features=10, out_features=384, bias=True)
        (beta_embed): Linear(in_features=10, out_features=384, bias=True)
      )
      (upsample1): Upsample(size=(8, 8), mode='bilinear')
      (upsample2): Upsample(size=(8, 8), mode='bilinear')
      (relu): ReLU()
      (conv_cbns): ModuleList(
        (0-1): 2 x Decoder_Conv_CBN(
          (conv): Conv2d(384, 384, kernel_size=(3, 3), stride=(1, 1), padding=same)
          (cbn): ConditionalBatchNorm2d(
            (bn): BatchNorm2d(384, eps=1e-05, momentum=0.1, affine=Fa

In [26]:
from cVAE_GAN_cifar10 import Discriminator_cifar10
discriminator=Discriminator_cifar10(device=device)


In [27]:
discriminator

Discriminator_cifar10(
  (embed): Embedding(10, 192)
  (dis_block0): DisBlock(
    (conv): Conv2d(3, 192, kernel_size=(1, 1), stride=(1, 1), padding=same)
    (downsample1): AvgPool2d(kernel_size=2, stride=2, padding=0)
    (downsample2): AvgPool2d(kernel_size=2, stride=2, padding=0)
    (bn_relu_conv): Sequential(
      (0): Dis_BN_Relu_Conv(
        (bn): BatchNorm2d(3, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu): ReLU()
        (conv): Conv2d(3, 192, kernel_size=(3, 3), stride=(1, 1), padding=same)
      )
      (1): Dis_BN_Relu_Conv(
        (bn): BatchNorm2d(192, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu): ReLU()
        (conv): Conv2d(192, 192, kernel_size=(3, 3), stride=(1, 1), padding=same)
      )
    )
  )
  (dis_block1): DisBlock(
    (conv): Conv2d(192, 192, kernel_size=(1, 1), stride=(1, 1), padding=same)
    (downsample1): AvgPool2d(kernel_size=2, stride=2, padding=0)
    (downsample2): AvgPool2d(kerne

In [28]:
from cVAE_GAN_cifar10 import Discriminator_cifar10
discriminator=Discriminator_cifar10(device=device)
score=discriminator(img,y)
score.shape

torch.Size([32, 1])

In [29]:
score

tensor([[ 4.4148],
        [12.4265],
        [-3.0569],
        [-2.1976],
        [ 0.1109],
        [11.4601],
        [-2.6982],
        [ 3.5257],
        [ 0.6883],
        [ 1.6492],
        [ 1.4529],
        [-1.3386],
        [-0.5951],
        [12.8178],
        [ 0.7714],
        [-1.7810],
        [ 2.6260],
        [ 7.9214],
        [ 1.0102],
        [-0.9212],
        [ 5.6685],
        [ 1.2905],
        [ 3.1672],
        [11.1367],
        [ 9.9189],
        [-1.4060],
        [ 2.6196],
        [ 1.9161],
        [ 4.2345],
        [ 3.4035],
        [ 0.4741],
        [ 0.4292]], device='cuda:0', grad_fn=<AddmmBackward0>)