In [1]:
import os
import torch.autograd
import torch.nn as nn



In [2]:
from Model.CVAE_PG_GAN import Gen_Block
# z=torch.randn(64,100)
# y=torch.randn(64,10)
# z0=torch.concat([z,y],dim=1)

# linear=nn.Linear(110,3*16*16)
gen_block=Gen_Block(3,32,3,1,1,100,10)
print(gen_block)
# x=linear(z0)
# print(x.shape)
# x=x.view(x.size(0),-1,16,16)
# print(x.shape)
# x1=gen_block(x,z0)
# print(x1.shape)


Gen_Block(
  (layer1): Sequential(
    (0): Conv2d(3, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): ReLU()
  )
  (layer2): Sequential(
    (0): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): ReLU()
  )
  (cbn1): ConditionalBatchNorm2d_for_skip_and_shared(
    (bn): BatchNorm2d(32, eps=0.0001, momentum=0.1, affine=False, track_running_stats=True)
    (gain): Linear(in_features=110, out_features=32, bias=False)
    (bias): Linear(in_features=110, out_features=32, bias=False)
  )
  (cbn2): ConditionalBatchNorm2d_for_skip_and_shared(
    (bn): BatchNorm2d(32, eps=0.0001, momentum=0.1, affine=False, track_running_stats=True)
    (gain): Linear(in_features=110, out_features=32, bias=False)
    (bias): Linear(in_features=110, out_features=32, bias=False)
  )
  (self_attn): Self_Attn(
    (conv1x1_theta): Conv2d(32, 4, kernel_size=(1, 1), stride=(1, 1), bias=False)
    (conv1x1_phi): Conv2d(32, 4, kernel_size=(1, 1), stride=(1, 1), bias=False)
    

In [3]:
import torch
from Model.CVAE_PG_GAN import CVAE
y=torch.randn(128,3,64,64)
cvae = CVAE(nz=100,
			 imSize=64,
             block_num=4,
             in_channel=3,
			 fSize=32,
             numLabels=10,
			 device='cpu')
print(cvae)
cvae.encode(y)


CVAE(
  (encLogVar): Linear(in_features=4096, out_features=100, bias=True)
  (encMu): Linear(in_features=4096, out_features=100, bias=True)
  (encY): Linear(in_features=4096, out_features=10, bias=True)
  (enc_layers): ModuleList(
    (0): Conv2d(3, 32, kernel_size=(5, 5), stride=(2, 2), padding=(2, 2))
    (1): Conv2d(32, 64, kernel_size=(5, 5), stride=(2, 2), padding=(2, 2))
    (2): Conv2d(64, 128, kernel_size=(5, 5), stride=(2, 2), padding=(2, 2))
    (3): Conv2d(128, 256, kernel_size=(5, 5), stride=(2, 2), padding=(2, 2))
  )
  (enc_attn_block): Self_Attn(
    (conv1x1_theta): Conv2d(256, 32, kernel_size=(1, 1), stride=(1, 1), bias=False)
    (conv1x1_phi): Conv2d(256, 32, kernel_size=(1, 1), stride=(1, 1), bias=False)
    (conv1x1_g): Conv2d(256, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
    (conv1x1_attn): Conv2d(128, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
    (maxpool): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (softma

e:\Project\ZLTProgram\GTSRB\Model\CVAE_PG_GAN.py:120: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  y = F.softmax(self.encY(x.detach()))


(tensor([[-0.0059,  0.0100, -0.0120,  ..., -0.0174,  0.0129, -0.0166],
         [-0.0156,  0.0003, -0.0032,  ..., -0.0011,  0.0118, -0.0030],
         [-0.0080,  0.0138,  0.0062,  ...,  0.0106,  0.0142,  0.0057],
         ...,
         [-0.0123,  0.0136, -0.0080,  ..., -0.0108, -0.0032, -0.0042],
         [-0.0114,  0.0212, -0.0031,  ..., -0.0101,  0.0146, -0.0072],
         [-0.0056,  0.0096,  0.0024,  ...,  0.0042,  0.0120, -0.0048]],
        grad_fn=<AddmmBackward0>),
 tensor([[ 0.0148, -0.0015,  0.0230,  ...,  0.0358, -0.0177,  0.0057],
         [ 0.0176, -0.0014,  0.0329,  ...,  0.0410, -0.0095,  0.0248],
         [ 0.0192, -0.0062,  0.0238,  ...,  0.0276, -0.0163,  0.0147],
         ...,
         [ 0.0131,  0.0017,  0.0332,  ...,  0.0243, -0.0079,  0.0171],
         [ 0.0171, -0.0168,  0.0266,  ...,  0.0297, -0.0249,  0.0291],
         [ 0.0110,  0.0008,  0.0284,  ...,  0.0355, -0.0162,  0.0234]],
        grad_fn=<AddmmBackward0>),
 tensor([[0.1020, 0.0989, 0.1021,  ..., 0.0988, 