In [19]:
import torch.nn as nn
from torchvision import transforms
import torch.nn.functional as F
import torch
import sys
sys.path.append("E:/Project/ZLTProgram/")
import os
os.environ['CUDA_LAUNCH_BLOCKING'] = '1' # 下面老是报错 shape 不一致
from Target_model import Target_model



In [20]:
import torch

# 假设您有形状为（64，1）的整数数据
integer_data = torch.randint(2, (64, 1))  # 随机生成0或1的整数数据
integer_data.shape


torch.Size([64, 1])

In [21]:
# 创建一个全零的独热编码标签张量
num_samples = integer_data.shape[0]
num_classes = 2
one_hot_labels = torch.zeros(num_samples, num_classes)

# 使用scatter_函数将整数数据映射到独热编码标签
one_hot_labels.scatter_(1, integer_data, 1)

# 打印独热编码标签
print(one_hot_labels)

tensor([[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [0., 1.],
        [1., 0.],
        [0., 1.],
        [0., 1.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [0., 1.],
        [1., 0.],
        [1., 0.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [1., 0.],
        [0., 1.],
        [1., 0.],
        [0., 1.],
        [1., 0.],
        [0., 1.],
        [1., 0.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [1., 0.],
        [1., 0.],
        [0., 1.],
        [0., 1.],
        [1., 0.],
        [1., 0.],
        [0., 1.],
        [1., 0.],
        [0., 1.],
        [0., 1.],
        [1., 0.],
        [0., 1.],
        [1., 0.],
        [1., 0.],
        [0., 1.],
        [1., 0.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [1., 0.],
        [0., 1.],
        [1., 0.],
        [1., 0.],
        [0

In [22]:
_, predicted = torch.max(one_hot_labels.data, 1)

In [23]:
predicted

tensor([0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1,
        0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1,
        1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0])

In [24]:
outputs=torch.randn(64,2)
outputs

tensor([[ 0.6537, -0.4748],
        [-0.5635, -0.5168],
        [ 2.1453,  0.4868],
        [-0.0117,  0.8430],
        [-0.2880, -1.0850],
        [ 0.6189, -0.4300],
        [ 0.0702, -0.6539],
        [ 0.1210,  0.0911],
        [ 1.3280, -1.0480],
        [ 0.0610, -1.1234],
        [ 0.8203,  1.7613],
        [-0.2943,  1.6459],
        [ 1.0593, -1.8615],
        [ 0.0951, -0.3363],
        [ 0.9062,  0.4223],
        [-0.5466,  1.1905],
        [ 0.4959, -1.4894],
        [ 1.0025,  0.3003],
        [-0.2213,  1.9657],
        [-0.8755, -2.3652],
        [ 0.9072, -1.3968],
        [ 0.3129,  0.9781],
        [ 0.8547,  0.4967],
        [ 0.1022, -1.0764],
        [ 1.3104,  0.1125],
        [ 0.3311, -0.4680],
        [-0.1106, -0.2436],
        [-0.6450, -1.6585],
        [-0.1850, -0.5674],
        [ 0.5025,  0.0034],
        [ 0.9945,  1.4520],
        [ 0.5428,  0.2636],
        [ 0.3607,  0.9166],
        [ 0.3445, -1.1694],
        [ 0.3275,  0.3315],
        [-0.0243,  1

In [ ]:
_, predicted = torch.max(one_hot_labels.data, 1)
predicted