In [1]:

import torch.nn as nn
import torch

In [2]:
# device = 'cuda' if torch.cuda.is_available() else 'cpu'
# block=Encoder_cifar10(80,device)
# img=torch.randn(128,3,32,32)
# img.shape

In [3]:
# block

In [4]:
# out,_,_=block(img)
# out.shape

In [5]:
# from cVAE_GAN_cifar10 import ConditionalBatchNorm2d
# num_features = 64  # 输入特征的通道数
# num_conditions = 10  # 类别数
# cbn=ConditionalBatchNorm2d(64,10)
# cbn

In [6]:

# condition = torch.zeros(32,10)  # 32样本的标签
# condition.shape
# condition


In [7]:
# input_data = torch.randn(32, num_features, 32, 32)
# input_data.shape


In [8]:
# output = cbn(input_data, condition)
# output.shape

In [9]:
# from cVAE_GAN_cifar10 import Decoder_cifar10,Encoder_cifar10
# device = 'cuda' if torch.cuda.is_available() else 'cpu'
# encoder=Encoder_cifar10(device=device)
# decoder=Decoder_cifar10(device=device)
# img=torch.randn(32,3,32,32).to(device)
# z,_,_=encoder(img)



In [10]:
z

tensor([[ 0.2602,  1.5583,  1.1365,  ...,  1.4674,  0.0174,  0.6552],
        [-1.0887,  1.7266, -1.4496,  ..., -1.0518,  0.7275, -1.9965],
        [-0.0031,  0.1548,  1.0807,  ..., -0.6144,  1.5263,  0.6056],
        ...,
        [ 1.0048,  1.8177,  0.2037,  ..., -0.4347,  0.1568,  0.9865],
        [ 0.3209,  1.1892,  0.0469,  ..., -1.0724, -1.5451, -0.2084],
        [-3.0097,  0.1170,  0.4446,  ..., -1.4209,  1.3428, -0.4924]],
       device='cuda:0', grad_fn=<AddBackward0>)

In [11]:
z.shape

torch.Size([32, 80])

In [12]:
y = torch.randint(low=0, high=9, size=(32,)).to(device)


In [13]:
img=decoder(z,y)

In [14]:
img

tensor([[[[ 8.0569e-02,  1.1307e-01,  1.1286e-01,  ..., -5.5681e-03,
            6.6413e-02, -2.5951e-02],
          [ 2.4207e-01,  9.8834e-02,  1.9910e-01,  ...,  1.5631e-02,
            2.2536e-01,  4.9805e-02],
          [ 3.1684e-01,  1.5610e-01, -9.7967e-02,  ..., -3.5694e-01,
           -2.2864e-01, -2.9059e-01],
          ...,
          [ 1.4212e-01,  1.4217e-01,  5.5895e-02,  ...,  2.1847e-01,
            2.1037e-01, -5.9748e-02],
          [ 4.8573e-02,  3.9703e-02, -1.4663e-03,  ...,  1.1005e-01,
            1.7826e-01, -6.7089e-02],
          [ 5.7316e-02,  6.3370e-02,  1.1962e-01,  ...,  2.2172e-01,
            1.4457e-01,  2.6165e-01]],

         [[ 2.4606e-01,  2.8792e-01,  2.5956e-01,  ...,  2.1358e-01,
            9.0143e-02, -3.2085e-01],
          [-6.9085e-02,  2.6566e-01,  2.7355e-01,  ..., -1.6252e-01,
           -2.1033e-01, -4.9805e-01],
          [ 8.4792e-02,  3.6032e-01,  3.3655e-01,  ...,  9.7298e-02,
           -2.5944e-01, -3.5202e-01],
          ...,
     

In [15]:
img.shape

torch.Size([32, 3, 32, 32])

In [16]:
decoder

Decoder_cifar10(
  (linear): Linear(in_features=20, out_features=6144, bias=True)
  (embed): Embedding(10, 128)
  (gen_blocks): ModuleList(
    (0): DecoderBlock(
      (conv): Conv2d(384, 384, kernel_size=(1, 1), stride=(1, 1), padding=same)
      (linear): Linear(in_features=148, out_features=10, bias=True)
      (cbn): ConditionalBatchNorm2d(
        (bn): BatchNorm2d(384, eps=1e-05, momentum=0.1, affine=False, track_running_stats=True)
        (gamma_embed): Linear(in_features=10, out_features=384, bias=True)
        (beta_embed): Linear(in_features=10, out_features=384, bias=True)
      )
      (upsample1): Upsample(size=(8, 8), mode='bilinear')
      (upsample2): Upsample(size=(8, 8), mode='bilinear')
      (relu): ReLU()
      (conv_cbns): ModuleList(
        (0-1): 2 x Decoder_Conv_CBN(
          (conv): Conv2d(384, 384, kernel_size=(3, 3), stride=(1, 1), padding=same)
          (cbn): ConditionalBatchNorm2d(
            (bn): BatchNorm2d(384, eps=1e-05, momentum=0.1, affine=Fa

In [17]:
from cVAE_GAN_cifar10 import Discriminator_cifar10
discriminator=Discriminator_cifar10(device=device)


In [18]:
discriminator

Discriminator_cifar10(
  (embed): Embedding(10, 192)
  (dis_block0): DisBlock(
    (conv): Conv2d(3, 192, kernel_size=(1, 1), stride=(1, 1), padding=same)
    (downsample1): AvgPool2d(kernel_size=2, stride=2, padding=0)
    (downsample2): AvgPool2d(kernel_size=2, stride=2, padding=0)
    (bn_relu_conv): Sequential(
      (0): Dis_BN_Relu_Conv(
        (bn): BatchNorm2d(3, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu): ReLU()
        (conv): Conv2d(3, 192, kernel_size=(3, 3), stride=(1, 1), padding=same)
      )
      (1): Dis_BN_Relu_Conv(
        (bn): BatchNorm2d(192, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu): ReLU()
        (conv): Conv2d(192, 192, kernel_size=(3, 3), stride=(1, 1), padding=same)
      )
    )
  )
  (dis_block1): DisBlock(
    (conv): Conv2d(192, 192, kernel_size=(1, 1), stride=(1, 1), padding=same)
    (downsample1): AvgPool2d(kernel_size=2, stride=2, padding=0)
    (downsample2): AvgPool2d(kerne

In [19]:
from cVAE_GAN_cifar10 import Discriminator_cifar10
discriminator=Discriminator_cifar10(device=device)
score=discriminator(img,y)
score.shape

torch.Size([32, 1])

In [20]:
score

tensor([[ 2.8632],
        [ 6.0770],
        [ 1.3480],
        [-4.7771],
        [ 8.8658],
        [-6.5485],
        [ 0.9432],
        [ 2.6607],
        [ 3.0489],
        [-5.2432],
        [ 1.8068],
        [-1.1706],
        [-0.0584],
        [ 1.3532],
        [-1.6888],
        [ 6.3777],
        [-4.6716],
        [ 5.6119],
        [21.1293],
        [ 4.6705],
        [-6.0032],
        [ 5.4434],
        [ 3.1332],
        [ 3.4111],
        [ 2.8303],
        [ 3.6022],
        [11.5742],
        [-0.1712],
        [-8.1517],
        [11.9145],
        [11.1970],
        [ 5.1995]], device='cuda:0', grad_fn=<AddmmBackward0>)